### ISSUE TITLE
ng build fails due to incorrect file name

### ISSUE THREAD

**Issue by trbryant2** [ibm-cloud-architecture/refarch-caseportal-app#1]
At the **Build** step, the **ng build** command fails due to an incorrect file name.  The incorrect file is **~/refarch-caseportal-app/src/app/features/telcodemo/customer/Customer.ts**   The correct file name is **~/refarch-caseportal-app/src/app/features/telcodemo/customer/customer.ts**

**Comment by jbcodeforce** [comment]
Thank you for the report. I fixed it. Strangely on my computer customer.ts was lowercase... git trap may be...
